
package br.com.fiap.stub_classes;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WineStockService", targetNamespace = "http://winery.fiap.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WineStockService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "placeOrder", targetNamespace = "http://winery.fiap.com.br/", className = "br.com.fiap.stub_classes.PlaceOrder")
    @ResponseWrapper(localName = "placeOrderResponse", targetNamespace = "http://winery.fiap.com.br/", className = "br.com.fiap.stub_classes.PlaceOrderResponse")
    @Action(input = "http://winery.fiap.com.br/WineStockService/placeOrderRequest", output = "http://winery.fiap.com.br/WineStockService/placeOrderResponse")
    public String placeOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMenu", targetNamespace = "http://winery.fiap.com.br/", className = "br.com.fiap.stub_classes.GetMenu")
    @ResponseWrapper(localName = "getMenuResponse", targetNamespace = "http://winery.fiap.com.br/", className = "br.com.fiap.stub_classes.GetMenuResponse")
    @Action(input = "http://winery.fiap.com.br/WineStockService/getMenuRequest", output = "http://winery.fiap.com.br/WineStockService/getMenuResponse")
    public String getMenu();

}
